### ISSUE TITLE
Match substring in case string

### ISSUE THREAD

**Issue by yosevu** [caderek/arrows#47]
Hello @caderek, very interesting library!

I've just started looking at it and I am wondering: is there a way to match a substring as a case value with multimethods if I don't have control of the string, but I still want to use a substring for a case value. I'm not really sure how this would work, but perhaps something like:

```javascript
const order = multi(
  (data, foodName) => // match a food substring from a method

  // Matches foodNames with 'cheese'
  method(/cheese/i, (data) => {
    return `Ordering ${data.foodName}!`
  }),

  // Matches foodNames with 'olives'
  method(/olives/i, (data) => {
    return `Ordering ${data.foodName}!'
  }),
)

order(data, 'Blue Cheese') // 'Ordering Blue Cheese!'
order(data, 'Aged Brie Cheese') // 'Ordering Aged Brie Cheese!'
order(data, 'gourmet black olives') // 'Ordering gourmet black olives!'
```
Is there another/better way to achieve this?

**Comment by yosevu** [comment]
Bump.

@caderek, I think the case object would have to be a [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) for this to work. Does that make sense?

> A Map's keys can be any value (including functions, objects, or any primitive).

**Comment by caderek** [comment]
Hey,
I just wanted to let you know that your use case inspired me to add regexp matching as a direct feature as you described:

```js
/**
 * Function with case values as regular expressions.
 * Matched by RegExp.prototype.test() method
 *
 * @param {RegExp} pattern
 * @returns {string} type
 */
const productCategory = multi(
  method(/wine/, 'wine'),
  method(/cheese/, 'cheese'),
  method(/milk/, 'milk'),
)

productCategory('blue cheese') // -> "cheese"
productCategory('red wine') // -> "wine"
productCategory('white wine from Germany') // -> "wine"
sendMessage('breadcrumbs') // -> "bread"
```

Thank you!

**Comment by yosevu** [comment]
Nice! Thanks for sharing @caderek. I'll have to revisit my use case and try this.
