### ISSUE TITLE
Suggestion: Add a tutorial to the README

### ISSUE THREAD

**Issue by viebel** [caderek/arrows#91]
Hello there!
This library really shines!!!!

I used it in a [blog post](https://blog.klipse.tech/javascript/2021/10/02/multimethod.html) in order to explain what multimethods are and how they provide polymorphism without the needs for objects.

If you like the article, please consider mentioning it in the README.

**Comment by caderek** [comment]
That's a great article!
I will definitelly add it to the README.
Thanks!
